### ISSUE TITLE
predict returned empty results.

### ISSUE THREAD

**Issue by huseinzol05** [lifeomic/sparkflow#17]
```
predictions = fitted_model.transform(encoded)
predictions.show(1)
+--------------------+--------------+---------+
|            features|        labels|predicted|
+--------------------+--------------+---------+
|(784,[132,133,134...|(10,[1],[1.0])|       []|
+--------------------+--------------+---------+
only showing top 1 row
```

I got empty `predicted`, all the source code is here, https://github.com/huseinzol05/Pyspark-ML/blob/master/sparkflow/1.mnist-sparkflow-feedforward.ipynb.

And I use docker to spawn a spark environment, can check here, https://github.com/huseinzol05/Pyspark-ML/blob/master/Dockerfile-cluster

Again, thanks!

**Comment by dmmiller612** [comment]
One note I'll throw in before I check this out on Monday is that we haven't tested this with Spark 2.4. However, with that in mind, with some of the optimizations that have been made in 2.4, we have talked about future versions only support 2.4.

**Comment by huseinzol05** [comment]
Oh really, I guess I just use Spark 2.3, maybe solve. Will post the result here later.

**Comment by dmmiller612** [comment]
Sounds good. From your docker container, it looks like it installed the most recent version of tensorflow. We have tested up to 1.10 so far. There was a major change in 1.7 with the graph construction. I am not aware of a major though for later versions.

**Comment by sudssf** [comment]
I am seeing same behavior.  I tried spark 2.3.1 , 2.3.2 , 2.3.4 & respective pyspark
tensorflow 1.12, 1.10.0, 1.7.0

sparkflow =  0.5.0

**Comment by dmmiller612** [comment]
Interesting. I'll take a look again.

**Comment by dmmiller612** [comment]
I was able to reproduce the issue on an Ubuntu docker image but not on Mac or Centos. I'll dig in now, and see what is going on. Thanks again for bringing this issue up.

**Comment by dmmiller612** [comment]
Added the prediction fix. This will have a breaking change for pyspark users using python 2 (We still support python 2, just a small behavior change). I will update sparkflow to 0.6 in pypi when I get home tonight.

**Comment by dmmiller612** [comment]
Version 0.6.0 is deployed. I also included a Dockerfile with a Makefile to test the simple-dnn file.
