### ISSUE TITLE
configurable port for parameter server 

### ISSUE THREAD

**Issue by alexzhang2010** [lifeomic/sparkflow#24]
Looks like the port used by the parameter server is 5000. Does sparkflow allows a configurable port?

**Comment by dmmiller612** [comment]
We don't at the moment. I will look at adding a parameter for it in the short future.

**Comment by dmmiller612** [comment]
https://github.com/lifeomic/sparkflow/pull/29. Port option added here. It will be available in sparkflow 0.7
